/* Bull'sHits audit and Now Playing: local cross-tab metadata and optional webhook. */
(()=>{const KEY='bullshits-playout-events-v1',NOW='bullshits-now-playing-v1',CFG='bullshits-now-playing-config-v1';
const broadcast=(state)=>{try{localStorage.setItem(NOW,JSON.stringify(state));}catch(e){console.warn('Now Playing unavailable',e)}
let cfg={};try{cfg=JSON.parse(localStorage.getItem(CFG)||'{}')}catch{}
if(cfg.enabled&&cfg.url&&/^https:\/\//i.test(cfg.url)){fetch(cfg.url,{method:'POST',mode:'cors',headers:{'Content-Type':'application/json'},body:JSON.stringify(state),keepalive:true}).catch(e=>console.warn('Now Playing webhook failed (check CORS / endpoint):',e));}
};
const ACTIVE='bullshits-active-plays-v1';const CARDKEY='bullshits-cut-cards-v1';const rights=(artist,title)=>{try{const norm=s=>String(s||'').trim().toLowerCase().replace(/[^a-z0-9]+/g,' ');const all=JSON.parse(localStorage.getItem(CARDKEY)||'{}');const card=all[norm(artist)+'|'+norm(title)]||{};return Object.fromEntries(['isrc','iswc','label','writers','publisher','album','year','version','mbid'].map(k=>[k,card[k]||'']))}catch{return {}}};window.bullLog=(kind,details={})=>{let active={};try{active=JSON.parse(localStorage.getItem(ACTIVE)||'{}')}catch{}const f=details.fader||'';if(kind==='PLAY'){details={...rights(details.artist,details.title),...details};active[f]={...rights(details.artist,details.title),title:details.title||'',artist:details.artist||'',startedAt:new Date().toISOString(),durationSeconds:Number(details.duration)||0,source:details.source||''};try{localStorage.setItem(ACTIVE,JSON.stringify(active))}catch{}}else if(kind==='STOP'||kind==='ENDED'){const started=active[f];if(started){details={...started,...details,playedSeconds:Math.max(0,Math.round((Date.now()-Date.parse(started.startedAt))/1000))};delete active[f];try{localStorage.setItem(ACTIVE,JSON.stringify(active))}catch{}}}const event={id:crypto.randomUUID(),at:new Date().toISOString(),kind,...details};try{const events=JSON.parse(localStorage.getItem(KEY)||'[]');events.push(event);localStorage.setItem(KEY,JSON.stringify(events.slice(-5000)))}catch(e){console.warn('Audit unavailable',e)}
try{const prev=JSON.parse(localStorage.getItem(NOW)||'null');const fader=details.fader||'';
if(kind==='PLAY'){broadcast({schema:'bullshits.nowplaying.v1',status:'PLAYING',title:details.title||'Untitled',artist:details.artist||'',startedAt:event.at,fader,source:details.source||'',durationSeconds:details.duration||0,updatedAt:event.at})}
else if((kind==='STOP'||kind==='ENDED')&&prev&&prev.status==='PLAYING'&&(prev.fader===fader||fader==='A/B'&&['A','B'].includes(prev.fader))){broadcast({...prev,status:'OFF AIR',updatedAt:event.at})}
}catch(e){console.warn('Now Playing update failed',e)}
};})();